erDiagram
    direction LR
    Project
    Release
    User_Story
    User_Story_Commit
    User_Story_Metadata
    Promotion
    Promoted_User_Story
    Deployment
    JobExecution
    Project |o..o{ Release : "Project"
    Release |o..o{ User_Story : "Release"
    User_Story ||--o{ User_Story_Commit : "User_Story"
    User_Story ||--o{ User_Story_Metadata : "User_Story"
    User_Story ||--o{ Promoted_User_Story : "User_Story"
    Promotion ||--o{ Promoted_User_Story : "Promotion"
    Promotion |o..o{ Deployment : "Promotion"
    Deployment |o..o{ JobExecution : "Deployment"
    Promotion |o..o{ JobExecution : "Promotion"
    User_Story_Commit |o..o{ JobExecution : "UserStoryCommit"
