erDiagram
    direction LR
    Project
    Deployment_Flow
    Deployment_Flow_Step
    Stage
    Stage_Connection
    Environment
    Org
    Git_Repository
    Deployment_Flow |o..o{ Project : "Deployment_Flow"
    Git_Repository |o..o{ Deployment_Flow : "Git_Repository"
    Deployment_Flow ||--o{ Deployment_Flow_Step : "Deployment_Flow"
    Environment |o..o{ Deployment_Flow_Step : "Destination_Environment"
    Environment |o..o{ Deployment_Flow_Step : "Source_Environment"
    Stage_Connection |o..o{ Deployment_Flow_Step : "Stage_Connection"
    Org |o..o{ Org : "Developer_Hub_Org"
    Environment |o..o{ Org : "Environment"
    Deployment_Flow ||--o{ Stage_Connection : "Pipeline"
    Stage ||--o{ Stage_Connection : "Stage"
    Stage_Connection |o..o{ Stage_Connection : "Next_Stage_Connection"
