erDiagram
    direction LR
    Deployment_Flow
    Environment
    Stage
    Quality_Gate_Rule
    Quality_Gate_Rule_Condition
    Automation_Rule
    JobStep
    Test
    ExtensionConfiguration
    JobExecution
    Result
    Environment |o..o{ JobExecution : "Destination"
    Deployment_Flow |o..o{ JobExecution : "Pipeline"
    Environment |o..o{ JobExecution : "Source"
    JobStep |o..o{ JobExecution : "Job_Step"
    JobExecution |o..o{ JobStep : "JobExecution"
    Result |o..o{ JobStep : "Result"
    Quality_Gate_Rule_Condition |o..o{ JobStep : "Quality_Gate_Rule_Condition"
    Quality_Gate_Rule |o..o{ JobStep : "Quality_Gate_Rule"
    JobStep |o..o{ Result : "JobStep"
    Test |o..o{ Result : "Test"
    Quality_Gate_Rule ||--o{ Quality_Gate_Rule_Condition : "Quality_Gate_Rule"
    Environment |o..o{ Quality_Gate_Rule_Condition : "Environment"
    Deployment_Flow |o..o{ Quality_Gate_Rule_Condition : "Pipeline"
    ExtensionConfiguration ||..o{ Quality_Gate_Rule_Condition : "Extension_Configuration"
    Stage |o..o{ Quality_Gate_Rule_Condition : "Stage"
    ExtensionConfiguration |o..o{ Test : "Integration"
    ExtensionConfiguration |o..o{ Test : "ExtensionConfiguration"
    JobExecution |o..o{ Test : "LatestJobExecution"
    JobExecution |o..o{ ExtensionConfiguration : "copadoQuality__Latest_Job_Execution"
    Deployment_Flow ||--o{ Automation_Rule : "Pipeline"
    Quality_Gate_Rule_Condition |o..o{ Automation_Rule : "Quality_Gate_Rule_Condition"
