erDiagram
    direction LR
    Project
    Release
    User_Story
    Epic
    Sprint
    Team
    User_Story_Task
    Project |o..o{ Release : "Project"
    Release |o..o{ Release : "Parent_Release"
    User_Story |o..o{ Release : "Artifact_User_Story"
    Epic |o..o{ User_Story : "Epic"
    Project |o..o{ User_Story : "Project"
    Release |o..o{ User_Story : "Release"
    Sprint |o..o{ User_Story : "Sprint"
    Team |o..o{ User_Story : "Team"
    Release |o..o{ Epic : "Release"
    Project |o..o{ Sprint : "Project"
    Release |o..o{ Sprint : "Release"
    Team |o..o{ Sprint : "Team"
    User_Story ||--o{ User_Story_Task : "User_Story"
